#!/usr/bin/env bash

set -eo pipefail

SECRETKEY=$2
SECRETVAL=$3

read() {
    aws secretsmanager get-secret-value --secret-id $1 --version-stage AWSCURRENT | grep SecretString | awk '{print substr($2, 1, length($2)-1)}'
    RETVAL=$?
    exit $RETVAL
}

write() {
    aws secretsmanager create-secret --name $1 --description "Created by aws-secrets-manager-cli because!" --secret-string $2
    RETVAL=$?
    exit $RETVAL
}

ensure() {
    aws secretsmanager describe-secret --secret-id $1
    if [ "$?" -eq "0" ]; then
        echo "$1 exists."
        RETVAL=0
    fi
    exit $RETVAL
}


case "$1" in
    read)
        read $SECRETKEY
        ;;
    write)
        write $SECRETKEY $SECRETVAL
        ;;
    ensure)
        ensure $SECRETKEY
        ;;
    *)
        echo "Usage: {read|write|ensure}"
        exit 1
        ;;
esac
exit $RETVAL
