#!/usr/bin/env bash

set -eo pipefail

SECRETKEY=$2

whoami=`whoami`
machine=`uname -n`
time=`date`

read() {
    aws secretsmanager get-secret-value --secret-id $1 --version-stage AWSCURRENT | grep SecretString | awk '{print substr($2, 1, length($2)-1)}' | awk '{print substr($1, 2, length($1)-2)}'
    RETVAL=$?
    exit $RETVAL
}

list() {
    aws secretsmanager list-secrets --output text | grep -i $1
}

case "$1" in
    read|get|r)
        read $SECRETKEY
        ;;
    list|l)
        list $SECRETKEY
        ;;    
    *)
        echo "Usage: {read|list}"
        exit 1
        ;;
esac
exit $RETVAL
